/// The storybook library added in database version 9.
///
/// The three original books live as hand-drawn painters keyed by their row id
/// in `story_scene.dart`. These are data instead: every page names a
/// [StoryShot] — a backdrop plus a few placed actors — and `StoryStage` draws
/// it. Rows are matched to this list by [StorySeed.key], which is stored on the
/// `storybooks.story_key` column, so ids never have to line up.
///
/// Three strands: good values, Malaysian culture, and science & nature.
library;

enum StoryBackdrop {
  kampung,
  home,
  school,
  market,
  garden,
  field,
  rainforest,
  river,
  beach,
  sea,
  underwater,
  sky,
  space,
}

enum StoryActor {
  // People
  boy,
  girl, // tudung
  girlPigtails,
  woman,
  atuk,
  nenek,
  // Animals
  ant,
  grasshopper,
  tortoise,
  hare,
  kancil,
  crocodile,
  turtle,
  crab,
  fish,
  bird,
  butterfly,
  caterpillar,
  // Nature
  egg,
  cocoon,
  sprout,
  sun,
  cloud,
  raindrop,
  moon,
  star,
  planet,
  planetRinged,
  earth,
  rainbow,
  fireworks,
  rambutan,
  // Things
  rocket,
  wallet,
  coins,
  umbrella,
  kite,
  ketupat,
  pelita,
  basket,
  grain,
  flag,
  kuih,
  cup,
  snackBag,
  toyCar,
  heart,
}

enum StoryFeel { happy, sad, surprised, sleepy }

enum StoryMotion { still, bob, sway, float, hop, fly }

/// One actor placed on a page. [x] and [y] are the actor's centre as fractions
/// of the page; [size] is its height as a fraction of the page's short side.
class StorySpot {
  final StoryActor actor;
  final double x;
  final double y;
  final double size;
  final StoryFeel feel;
  final StoryMotion motion;
  final bool flip;

  /// Optional ARGB override for the actor's main colour (shirt, wings, planet).
  final int? tint;

  const StorySpot(
    this.actor,
    this.x,
    this.y,
    this.size, {
    this.feel = StoryFeel.happy,
    this.motion = StoryMotion.bob,
    this.flip = false,
    this.tint,
  });
}

class StoryShot {
  final StoryBackdrop backdrop;
  final bool night;
  final bool rain;
  final List<StorySpot> actors;

  const StoryShot(this.backdrop, this.actors, {this.night = false, this.rain = false});
}

class StoryPageSeed {
  final String text;
  final String textMs;
  final StoryShot shot;

  const StoryPageSeed(this.text, this.textMs, this.shot);
}

class StorySeed {
  final String key;
  final String title;
  final String titleMs;
  final String description;
  final String coverEmoji;

  /// Matched by name against the `categories` table.
  final String category;
  final String ageGroup;
  final List<StoryPageSeed> pages;

  const StorySeed({
    required this.key,
    required this.title,
    required this.titleMs,
    required this.description,
    required this.coverEmoji,
    required this.category,
    required this.ageGroup,
    required this.pages,
  });
}

StorySeed? storySeedFor(String? key) {
  if (key == null) return null;
  for (final s in kStoryLibrary) {
    if (s.key == key) return s;
  }
  return null;
}

// Short aliases keep the page tables readable.
typedef _P = StoryPageSeed;
typedef _S = StoryShot;
typedef _A = StorySpot;
typedef _B = StoryBackdrop;
typedef _R = StoryActor;
typedef _F = StoryFeel;
typedef _M = StoryMotion;

const int _purple = 0xFF9B6BD6;
const int _grey = 0xFF9AA5B8;
const int _red = 0xFFE74C3C;

const List<StorySeed> kStoryLibrary = [
  // ── Good values ──────────────────────────────────────────────────────────
  StorySeed(
    key: 'honest_wallet',
    title: 'Ali and the Lost Wallet',
    titleMs: 'Ali dan Dompet yang Hilang',
    description: 'Ali finds a wallet and chooses to be honest.',
    coverEmoji: '👛',
    category: 'Language',
    ageGroup: 'primary',
    pages: [
      _P('Ali walked to the pasar malam with Atuk. The stalls glowed with bright lights.',
          'Ali berjalan ke pasar malam bersama Atuk. Gerai-gerai bersinar dengan lampu yang terang.',
          _S(_B.market, night: true, [_A(_R.boy, 0.4, 0.6, 0.34), _A(_R.atuk, 0.62, 0.56, 0.44)])),
      _P('Suddenly, Ali saw something on the ground. It was a brown wallet!',
          'Tiba-tiba, Ali ternampak sesuatu di atas tanah. Ia sebuah dompet coklat!',
          _S(_B.market, night: true, [_A(_R.boy, 0.38, 0.58, 0.36, feel: _F.surprised), _A(_R.wallet, 0.64, 0.66, 0.12, motion: _M.still)])),
      _P('Inside were many ringgit notes. "Wow, I could buy so many toys!" Ali thought.',
          'Di dalamnya ada banyak wang kertas. "Wah, boleh beli banyak mainan!" fikir Ali.',
          _S(_B.market, night: true, [_A(_R.boy, 0.36, 0.58, 0.36, feel: _F.surprised), _A(_R.wallet, 0.62, 0.42, 0.14, motion: _M.float), _A(_R.toyCar, 0.8, 0.26, 0.1, motion: _M.float)])),
      _P('But Ali remembered what Atuk always said: "What is not ours, we must return."',
          'Tetapi Ali teringat kata Atuk: "Barang yang bukan milik kita, mesti dipulangkan."',
          _S(_B.market, night: true, [_A(_R.atuk, 0.34, 0.55, 0.44), _A(_R.boy, 0.64, 0.6, 0.34, flip: true), _A(_R.heart, 0.5, 0.26, 0.1, motion: _M.float)])),
      _P('Inside the wallet was a card with a name on it: Puan Siti.',
          'Dalam dompet itu ada sekeping kad dengan nama: Puan Siti.',
          _S(_B.market, night: true, [_A(_R.boy, 0.42, 0.58, 0.36), _A(_R.wallet, 0.66, 0.5, 0.16, motion: _M.sway)])),
      _P('Ali and Atuk looked everywhere. Then they saw a woman who looked very worried.',
          'Ali dan Atuk mencari di merata tempat. Kemudian mereka nampak seorang wanita yang kelihatan sangat risau.',
          _S(_B.market, night: true, [_A(_R.boy, 0.2, 0.6, 0.32), _A(_R.atuk, 0.38, 0.56, 0.42), _A(_R.woman, 0.74, 0.56, 0.42, feel: _F.sad, flip: true)])),
      _P('"Are you Puan Siti?" asked Ali. "Yes! I lost my wallet," she said.',
          '"Makcik ini Puan Siti?" tanya Ali. "Ya! Makcik kehilangan dompet," katanya.',
          _S(_B.market, night: true, [_A(_R.boy, 0.34, 0.6, 0.34), _A(_R.wallet, 0.5, 0.5, 0.1, motion: _M.bob), _A(_R.woman, 0.68, 0.56, 0.42, feel: _F.surprised, flip: true)])),
      _P('Ali gave back the wallet. Puan Siti smiled so wide. "Thank you, honest boy!"',
          'Ali memulangkan dompet itu. Puan Siti tersenyum lebar. "Terima kasih, budak yang jujur!"',
          _S(_B.market, night: true, [_A(_R.boy, 0.36, 0.6, 0.34, motion: _M.hop), _A(_R.woman, 0.64, 0.56, 0.42, flip: true), _A(_R.heart, 0.5, 0.28, 0.1, motion: _M.float)])),
      _P('Atuk patted Ali\'s head. "I am proud of you." Being honest feels good!',
          'Atuk mengusap kepala Ali. "Atuk bangga dengan kamu." Jujur itu indah!',
          _S(_B.kampung, night: true, [_A(_R.atuk, 0.4, 0.56, 0.44), _A(_R.boy, 0.6, 0.6, 0.34, flip: true, motion: _M.hop), _A(_R.star, 0.5, 0.18, 0.12, motion: _M.float)])),
    ],
  ),
  StorySeed(
    key: 'ant_grasshopper',
    title: 'The Ant and the Grasshopper',
    titleMs: 'Semut dan Belalang',
    description: 'A hard-working ant and a playful grasshopper learn to help each other.',
    coverEmoji: '🐜',
    category: 'Animals',
    ageGroup: 'all',
    pages: [
      _P('On a sunny day, a little ant carried a grain of rice across the garden.',
          'Pada hari yang cerah, seekor semut kecil membawa sebutir beras merentasi taman.',
          _S(_B.garden, [_A(_R.sun, 0.82, 0.16, 0.18, motion: _M.sway), _A(_R.ant, 0.46, 0.66, 0.16), _A(_R.grain, 0.5, 0.56, 0.06, motion: _M.bob)])),
      _P('Grasshopper played music and danced. "Come and play with me, Ant!"',
          'Belalang bermain muzik dan menari. "Marilah bermain dengan saya, Semut!"',
          _S(_B.garden, [_A(_R.grasshopper, 0.62, 0.6, 0.24, motion: _M.hop, flip: true), _A(_R.ant, 0.3, 0.68, 0.15)])),
      _P('"Sorry, I must store food before the rainy season comes," said Ant.',
          '"Maaf, saya perlu simpan makanan sebelum musim hujan tiba," kata Semut.',
          _S(_B.garden, [_A(_R.ant, 0.36, 0.68, 0.16), _A(_R.basket, 0.62, 0.66, 0.18, motion: _M.still), _A(_R.grasshopper, 0.84, 0.58, 0.2, flip: true)])),
      _P('Day after day, the ants worked hard. Grasshopper just sang and slept.',
          'Hari demi hari, semut-semut bekerja keras. Belalang hanya menyanyi dan tidur.',
          _S(_B.garden, [_A(_R.ant, 0.18, 0.7, 0.13), _A(_R.ant, 0.34, 0.7, 0.13), _A(_R.ant, 0.5, 0.7, 0.13), _A(_R.grasshopper, 0.78, 0.6, 0.2, feel: _F.sleepy, motion: _M.still, flip: true)])),
      _P('Then the dark clouds came. Rain fell and fell for many days.',
          'Kemudian awan gelap datang. Hujan turun berhari-hari lamanya.',
          _S(_B.garden, rain: true, [_A(_R.cloud, 0.34, 0.18, 0.18, feel: _F.sad, tint: _grey, motion: _M.fly), _A(_R.cloud, 0.7, 0.22, 0.2, feel: _F.sad, tint: _grey, motion: _M.fly)])),
      _P('Grasshopper was cold and hungry. There was no food anywhere.',
          'Belalang kesejukan dan kelaparan. Tiada makanan di mana-mana.',
          _S(_B.garden, rain: true, [_A(_R.grasshopper, 0.5, 0.62, 0.26, feel: _F.sad, motion: _M.sway)])),
      _P('He knocked on Ant\'s door. "Please, can you help me?"',
          'Dia mengetuk pintu rumah Semut. "Tolonglah, bolehkah awak bantu saya?"',
          _S(_B.garden, rain: true, [_A(_R.grasshopper, 0.64, 0.6, 0.24, feel: _F.sad, flip: true), _A(_R.ant, 0.32, 0.68, 0.16, feel: _F.surprised)])),
      _P('Ant shared her food. "Friends help each other," she said kindly.',
          'Semut berkongsi makanannya. "Kawan mesti tolong-menolong," katanya dengan baik.',
          _S(_B.garden, rain: true, [_A(_R.ant, 0.3, 0.68, 0.16), _A(_R.basket, 0.5, 0.66, 0.16, motion: _M.still), _A(_R.grasshopper, 0.72, 0.6, 0.22, flip: true), _A(_R.heart, 0.5, 0.36, 0.08, motion: _M.float)])),
      _P('Grasshopper said, "Thank you. Next year, I will work hard too!"',
          'Belalang berkata, "Terima kasih. Tahun depan, saya pun akan bekerja keras!"',
          _S(_B.garden, [_A(_R.grasshopper, 0.56, 0.6, 0.26, motion: _M.hop), _A(_R.ant, 0.28, 0.68, 0.15)])),
      _P('When the sun came back, they worked and played together.',
          'Apabila matahari muncul semula, mereka bekerja dan bermain bersama-sama.',
          _S(_B.garden, [_A(_R.rainbow, 0.5, 0.36, 0.34, motion: _M.still), _A(_R.sun, 0.84, 0.14, 0.16, motion: _M.sway), _A(_R.ant, 0.32, 0.68, 0.15, motion: _M.hop), _A(_R.grasshopper, 0.66, 0.6, 0.22, motion: _M.hop, flip: true)])),
    ],
  ),
  StorySeed(
    key: 'tortoise_hare',
    title: 'The Tortoise and the Hare',
    titleMs: 'Arnab dan Kura-kura',
    description: 'Slow and steady wins the race.',
    coverEmoji: '🐢',
    category: 'Animals',
    ageGroup: 'preschool',
    pages: [
      _P('Hare was the fastest animal in the field. "Nobody can beat me!" he boasted.',
          'Arnab ialah haiwan paling laju di padang. "Tiada siapa boleh kalahkan saya!" katanya dengan sombong.',
          _S(_B.field, [_A(_R.hare, 0.5, 0.6, 0.28, motion: _M.hop)])),
      _P('Tortoise walked by, slowly. "Let\'s have a race," said Tortoise calmly.',
          'Kura-kura lalu dengan perlahan. "Mari kita berlumba," kata Kura-kura dengan tenang.',
          _S(_B.field, [_A(_R.hare, 0.3, 0.6, 0.26, feel: _F.surprised), _A(_R.tortoise, 0.68, 0.66, 0.2, flip: true)])),
      _P('All the animals laughed. But the race began! Ready, set, go!',
          'Semua haiwan ketawa. Tetapi perlumbaan pun bermula! Sedia, mula!',
          _S(_B.field, [_A(_R.bird, 0.2, 0.24, 0.1, motion: _M.fly), _A(_R.bird, 0.78, 0.3, 0.09, motion: _M.fly, flip: true), _A(_R.hare, 0.36, 0.62, 0.24), _A(_R.tortoise, 0.6, 0.67, 0.18), _A(_R.flag, 0.14, 0.58, 0.24, motion: _M.sway)])),
      _P('Hare zoomed far ahead. Tortoise walked step by step.',
          'Arnab berlari jauh ke depan. Kura-kura berjalan selangkah demi selangkah.',
          _S(_B.field, [_A(_R.hare, 0.8, 0.58, 0.22, motion: _M.hop), _A(_R.tortoise, 0.24, 0.67, 0.18)])),
      _P('"Tortoise is so slow. I\'ll take a nap," said Hare under a shady tree.',
          '"Kura-kura sangat lambat. Baik saya tidur sekejap," kata Arnab di bawah pokok yang redup.',
          _S(_B.field, [_A(_R.hare, 0.66, 0.64, 0.24, feel: _F.sleepy, motion: _M.still)])),
      _P('Tortoise did not stop. Slow and steady, he kept on going.',
          'Kura-kura tidak berhenti. Perlahan-lahan tetapi pasti, dia terus berjalan.',
          _S(_B.field, [_A(_R.tortoise, 0.44, 0.67, 0.2), _A(_R.sun, 0.84, 0.16, 0.16, motion: _M.sway)])),
      _P('Tortoise passed the sleeping Hare. The finish line was near!',
          'Kura-kura melepasi Arnab yang sedang tidur. Garisan penamat sudah dekat!',
          _S(_B.field, [_A(_R.hare, 0.24, 0.64, 0.22, feel: _F.sleepy, motion: _M.still), _A(_R.tortoise, 0.56, 0.67, 0.18), _A(_R.flag, 0.86, 0.58, 0.24, motion: _M.sway)])),
      _P('Hare woke up and ran as fast as he could. But it was too late!',
          'Arnab terjaga dan berlari selaju-lajunya. Tetapi sudah terlambat!',
          _S(_B.field, [_A(_R.hare, 0.36, 0.6, 0.24, feel: _F.surprised, motion: _M.hop), _A(_R.tortoise, 0.72, 0.67, 0.18), _A(_R.flag, 0.86, 0.58, 0.24, motion: _M.sway)])),
      _P('Tortoise won! All the animals cheered for him.',
          'Kura-kura menang! Semua haiwan bersorak untuknya.',
          _S(_B.field, [_A(_R.tortoise, 0.5, 0.64, 0.22, motion: _M.hop), _A(_R.bird, 0.26, 0.3, 0.1, motion: _M.fly), _A(_R.bird, 0.74, 0.26, 0.1, motion: _M.fly, flip: true), _A(_R.fireworks, 0.5, 0.24, 0.28, motion: _M.still)])),
      _P('Hare said sorry. "I learned never to look down on others."',
          'Arnab meminta maaf. "Saya belajar untuk tidak memandang rendah orang lain."',
          _S(_B.field, [_A(_R.hare, 0.34, 0.62, 0.24), _A(_R.tortoise, 0.64, 0.67, 0.18, flip: true), _A(_R.heart, 0.5, 0.36, 0.08, motion: _M.float)])),
    ],
  ),
  StorySeed(
    key: 'shared_umbrella',
    title: 'The Shared Umbrella',
    titleMs: 'Payung Kongsi',
    description: 'Aina shares her umbrella on a rainy day.',
    coverEmoji: '☂️',
    category: 'Language',
    ageGroup: 'preschool',
    pages: [
      _P('The school bell rang. It was time to go home.',
          'Loceng sekolah berbunyi. Sudah tiba masa untuk pulang.',
          _S(_B.school, [_A(_R.girl, 0.5, 0.6, 0.34, motion: _M.hop)])),
      _P('Aina looked outside. Dark clouds filled the sky.',
          'Aina melihat ke luar. Awan gelap memenuhi langit.',
          _S(_B.school, [_A(_R.cloud, 0.3, 0.16, 0.16, tint: _grey, feel: _F.sad, motion: _M.fly), _A(_R.cloud, 0.72, 0.2, 0.18, tint: _grey, feel: _F.sad, motion: _M.fly), _A(_R.girl, 0.5, 0.6, 0.34, feel: _F.surprised)])),
      _P('Then the rain poured down! Luckily, Aina had her yellow umbrella.',
          'Kemudian hujan turun dengan lebat! Nasib baik Aina membawa payung kuningnya.',
          _S(_B.school, rain: true, [_A(_R.umbrella, 0.5, 0.42, 0.28, motion: _M.sway), _A(_R.girl, 0.5, 0.62, 0.32)])),
      _P('At the gate, she saw Ravi. He had no umbrella, and he looked sad.',
          'Di pintu pagar, dia nampak Ravi. Ravi tiada payung, dan dia kelihatan sedih.',
          _S(_B.school, rain: true, [_A(_R.umbrella, 0.3, 0.42, 0.26, motion: _M.sway), _A(_R.girl, 0.3, 0.62, 0.3), _A(_R.boy, 0.72, 0.62, 0.3, feel: _F.sad, flip: true, tint: 0xFF3FA7F5)])),
      _P('Aina thought, "If I share, we will both be a little wet. But no one will be soaked."',
          'Aina berfikir, "Kalau saya berkongsi, kami berdua basah sedikit. Tetapi tiada siapa basah kuyup."',
          _S(_B.school, rain: true, [_A(_R.umbrella, 0.4, 0.42, 0.26, motion: _M.sway), _A(_R.girl, 0.4, 0.62, 0.3, feel: _F.surprised), _A(_R.heart, 0.62, 0.3, 0.08, motion: _M.float)])),
      _P('"Ravi, come under my umbrella!" said Aina with a smile.',
          '"Ravi, marilah berteduh di bawah payung saya!" kata Aina sambil tersenyum.',
          _S(_B.school, rain: true, [_A(_R.umbrella, 0.5, 0.4, 0.32, motion: _M.sway), _A(_R.girl, 0.4, 0.62, 0.3), _A(_R.boy, 0.6, 0.62, 0.3, feel: _F.surprised, flip: true, tint: 0xFF3FA7F5)])),
      _P('They walked together, jumping over puddles and laughing.',
          'Mereka berjalan bersama, melompat melepasi lopak air sambil ketawa.',
          _S(_B.field, rain: true, [_A(_R.umbrella, 0.5, 0.4, 0.32, motion: _M.hop), _A(_R.girl, 0.4, 0.62, 0.3, motion: _M.hop), _A(_R.boy, 0.6, 0.62, 0.3, motion: _M.hop, tint: 0xFF3FA7F5)])),
      _P('Ravi\'s mother was waiting at home. "Thank you for helping Ravi," she said.',
          'Ibu Ravi sedang menunggu di rumah. "Terima kasih kerana membantu Ravi," katanya.',
          _S(_B.kampung, rain: true, [_A(_R.girl, 0.26, 0.62, 0.3), _A(_R.boy, 0.46, 0.62, 0.3, tint: 0xFF3FA7F5), _A(_R.woman, 0.72, 0.56, 0.42, flip: true, tint: 0xFFE85D9C)])),
      _P('The next day, Ravi brought kuih for Aina. Sharing makes good friends!',
          'Keesokan harinya, Ravi membawa kuih untuk Aina. Berkongsi merapatkan persahabatan!',
          _S(_B.school, [_A(_R.rainbow, 0.5, 0.3, 0.3, motion: _M.still), _A(_R.girl, 0.34, 0.62, 0.3), _A(_R.kuih, 0.5, 0.58, 0.1, motion: _M.float), _A(_R.boy, 0.66, 0.62, 0.3, flip: true, tint: 0xFF3FA7F5)])),
    ],
  ),

  // ── Malaysian culture ────────────────────────────────────────────────────
  StorySeed(
    key: 'kancil_crocodile',
    title: 'Sang Kancil and the Crocodiles',
    titleMs: 'Sang Kancil dan Buaya',
    description: 'The clever mouse deer crosses a river full of crocodiles.',
    coverEmoji: '🦌',
    category: 'Animals',
    ageGroup: 'all',
    pages: [
      _P('Deep in the forest lived Sang Kancil, a small but very clever mouse deer.',
          'Di dalam hutan tinggal Sang Kancil, seekor kancil yang kecil tetapi sangat bijak.',
          _S(_B.rainforest, [_A(_R.kancil, 0.5, 0.62, 0.28)])),
      _P('One day, Kancil saw sweet rambutans on the other side of the river.',
          'Pada suatu hari, Kancil nampak buah rambutan yang manis di seberang sungai.',
          _S(_B.river, [_A(_R.kancil, 0.22, 0.7, 0.22), _A(_R.rambutan, 0.74, 0.2, 0.2, motion: _M.sway)])),
      _P('But the river was full of hungry crocodiles!',
          'Tetapi sungai itu penuh dengan buaya yang lapar!',
          _S(_B.river, [_A(_R.crocodile, 0.3, 0.52, 0.12, motion: _M.float), _A(_R.crocodile, 0.72, 0.58, 0.12, flip: true, motion: _M.float), _A(_R.kancil, 0.16, 0.7, 0.2, feel: _F.surprised)])),
      _P('Kancil had an idea. "The King has ordered me to count all the crocodiles!"',
          'Kancil mendapat akal. "Raja memerintahkan aku mengira semua buaya!"',
          _S(_B.river, [_A(_R.kancil, 0.3, 0.7, 0.22), _A(_R.star, 0.42, 0.56, 0.08, motion: _M.float), _A(_R.crocodile, 0.66, 0.54, 0.12, flip: true, feel: _F.surprised, motion: _M.float)])),
      _P('"Line up across the river, so I can count you," said Kancil.',
          '"Berbarislah merentasi sungai supaya aku boleh mengira kamu," kata Kancil.',
          _S(_B.river, [_A(_R.kancil, 0.16, 0.7, 0.2), _A(_R.crocodile, 0.36, 0.52, 0.1, motion: _M.float), _A(_R.crocodile, 0.64, 0.58, 0.1, motion: _M.float)])),
      _P('The crocodiles lined up. Kancil jumped on their backs: "One, two, three, four!"',
          'Buaya-buaya pun berbaris. Kancil melompat di atas belakang mereka: "Satu, dua, tiga, empat!"',
          _S(_B.river, [_A(_R.crocodile, 0.2, 0.54, 0.1, motion: _M.still), _A(_R.crocodile, 0.5, 0.54, 0.1, motion: _M.still), _A(_R.crocodile, 0.8, 0.54, 0.1, motion: _M.still), _A(_R.kancil, 0.44, 0.42, 0.18, motion: _M.hop)])),
      _P('"Five, six, seven!" Hop! Kancil landed on the other side.',
          '"Lima, enam, tujuh!" Lompat! Kancil mendarat di seberang sungai.',
          _S(_B.river, [_A(_R.crocodile, 0.3, 0.54, 0.1, motion: _M.still), _A(_R.crocodile, 0.6, 0.54, 0.1, motion: _M.still), _A(_R.kancil, 0.8, 0.26, 0.2, motion: _M.hop)])),
      _P('"Thank you, crocodiles! There was no counting order after all!"',
          '"Terima kasih, buaya! Sebenarnya tiada perintah pun!"',
          _S(_B.river, [_A(_R.kancil, 0.78, 0.26, 0.2, flip: true), _A(_R.crocodile, 0.36, 0.54, 0.12, feel: _F.surprised, motion: _M.float)])),
      _P('The crocodiles were cross, but Kancil was already eating rambutans.',
          'Buaya-buaya berasa geram, tetapi Kancil sudah pun makan buah rambutan.',
          _S(_B.rainforest, [_A(_R.kancil, 0.44, 0.62, 0.26), _A(_R.rambutan, 0.7, 0.5, 0.16, motion: _M.sway)])),
      _P('Kancil used his brain, not his strength. But remember, tricking others is not kind!',
          'Kancil menggunakan akal, bukan kekuatan. Tetapi ingat, menipu orang lain bukanlah perbuatan yang baik!',
          _S(_B.rainforest, [_A(_R.kancil, 0.5, 0.62, 0.28, motion: _M.hop), _A(_R.heart, 0.5, 0.3, 0.08, motion: _M.float)])),
    ],
  ),
  StorySeed(
    key: 'atuk_wau',
    title: 'Atuk\'s Wau Bulan',
    titleMs: 'Wau Bulan Atuk',
    description: 'Amir and Atuk build and fly a traditional moon kite.',
    coverEmoji: '🪁',
    category: 'Arts & Craft',
    ageGroup: 'all',
    pages: [
      _P('During the school holidays, Amir visited Atuk in the kampung.',
          'Semasa cuti sekolah, Amir melawat Atuk di kampung.',
          _S(_B.kampung, [_A(_R.boy, 0.38, 0.62, 0.32, motion: _M.hop), _A(_R.atuk, 0.6, 0.56, 0.44, flip: true)])),
      _P('Atuk showed Amir bamboo, paper and glue. "Today we will make a wau!"',
          'Atuk menunjukkan buluh, kertas dan gam kepada Amir. "Hari ini kita buat wau!"',
          _S(_B.home, [_A(_R.atuk, 0.32, 0.56, 0.44), _A(_R.boy, 0.68, 0.62, 0.32, feel: _F.surprised, flip: true)])),
      _P('A wau bulan is a Malaysian kite shaped like a crescent moon.',
          'Wau bulan ialah layang-layang tradisional Malaysia yang berbentuk seperti bulan sabit.',
          _S(_B.home, [_A(_R.kite, 0.5, 0.4, 0.4, motion: _M.sway)])),
      _P('They cut the bamboo and tied the frame carefully. It took patience!',
          'Mereka memotong buluh dan mengikat rangkanya dengan teliti. Ia memerlukan kesabaran!',
          _S(_B.home, [_A(_R.atuk, 0.24, 0.56, 0.42), _A(_R.kite, 0.5, 0.5, 0.22, motion: _M.still, tint: 0xFFE8DCC0), _A(_R.boy, 0.76, 0.62, 0.3, flip: true)])),
      _P('Amir painted beautiful flower patterns in red, yellow and blue.',
          'Amir melukis corak bunga yang cantik dengan warna merah, kuning dan biru.',
          _S(_B.home, [_A(_R.boy, 0.3, 0.62, 0.32), _A(_R.kite, 0.64, 0.46, 0.3, motion: _M.bob)])),
      _P('The next morning, the wind was strong. "Perfect for flying!" said Atuk.',
          'Keesokan paginya, angin bertiup kencang. "Sesuai untuk menerbangkan wau!" kata Atuk.',
          _S(_B.field, [_A(_R.atuk, 0.34, 0.56, 0.44), _A(_R.boy, 0.62, 0.62, 0.32, flip: true), _A(_R.kite, 0.84, 0.3, 0.2, motion: _M.sway)])),
      _P('Amir ran, but the wau fell down. Once, twice, three times!',
          'Amir berlari, tetapi wau itu jatuh. Sekali, dua kali, tiga kali!',
          _S(_B.field, [_A(_R.boy, 0.4, 0.62, 0.32, feel: _F.sad), _A(_R.kite, 0.68, 0.64, 0.18, motion: _M.still)])),
      _P('"Don\'t give up. Feel the wind, then let the string out slowly," said Atuk.',
          '"Jangan putus asa. Rasakan angin, kemudian lepaskan tali perlahan-lahan," kata Atuk.',
          _S(_B.field, [_A(_R.atuk, 0.36, 0.56, 0.44), _A(_R.boy, 0.64, 0.62, 0.32, flip: true, feel: _F.surprised), _A(_R.heart, 0.5, 0.3, 0.08, motion: _M.float)])),
      _P('Up, up, up! The wau flew high and made a humming sound.',
          'Naik, naik, naik! Wau itu terbang tinggi dan berbunyi mendengung.',
          _S(_B.sky, [_A(_R.kite, 0.56, 0.36, 0.34, motion: _M.fly), _A(_R.bird, 0.24, 0.24, 0.1, motion: _M.fly), _A(_R.cloud, 0.8, 0.6, 0.16, motion: _M.fly)])),
      _P('Amir hugged Atuk. "This is the best holiday ever!"',
          'Amir memeluk Atuk. "Inilah cuti yang paling seronok!"',
          _S(_B.field, [_A(_R.kite, 0.76, 0.2, 0.2, motion: _M.fly), _A(_R.atuk, 0.42, 0.56, 0.44), _A(_R.boy, 0.58, 0.62, 0.32, flip: true, motion: _M.hop)])),
    ],
  ),
  StorySeed(
    key: 'raya_kampung',
    title: 'Hari Raya in the Kampung',
    titleMs: 'Pagi Raya di Kampung',
    description: 'Sara celebrates Hari Raya with her family and friends.',
    coverEmoji: '🌙',
    category: 'Language',
    ageGroup: 'all',
    pages: [
      _P('On the night before Raya, pelita lamps glowed all around Nenek\'s house.',
          'Pada malam Raya, pelita menyala di sekeliling rumah Nenek.',
          _S(_B.kampung, night: true, [_A(_R.pelita, 0.14, 0.64, 0.22, motion: _M.still), _A(_R.pelita, 0.86, 0.64, 0.22, motion: _M.still), _A(_R.girl, 0.5, 0.62, 0.32, tint: _purple)])),
      _P('Nenek and Ibu wove ketupat from young coconut leaves.',
          'Nenek dan Ibu menganyam ketupat daripada daun kelapa muda.',
          _S(_B.home, night: true, [_A(_R.nenek, 0.28, 0.58, 0.4), _A(_R.ketupat, 0.5, 0.5, 0.14, motion: _M.sway), _A(_R.woman, 0.72, 0.56, 0.42, flip: true)])),
      _P('Sara tried too. Her ketupat was a little crooked, but Nenek said it was perfect.',
          'Sara pun mencuba. Ketupatnya sedikit senget, tetapi Nenek kata ia sempurna.',
          _S(_B.home, night: true, [_A(_R.nenek, 0.3, 0.58, 0.4), _A(_R.girl, 0.66, 0.62, 0.3, flip: true, tint: _purple), _A(_R.ketupat, 0.5, 0.44, 0.12, motion: _M.sway)])),
      _P('In the morning, everyone wore new baju raya. Sara\'s was purple!',
          'Pada waktu pagi, semua orang memakai baju raya baharu. Baju Sara berwarna ungu!',
          _S(_B.kampung, [_A(_R.woman, 0.22, 0.56, 0.42, tint: 0xFF2BB5A0), _A(_R.girl, 0.5, 0.62, 0.32, tint: _purple, motion: _M.hop), _A(_R.boy, 0.78, 0.62, 0.32, flip: true, tint: 0xFF2BB5A0)])),
      _P('Sara held Nenek\'s hand and kissed it. "Maaf zahir dan batin, Nenek."',
          'Sara bersalaman dan mencium tangan Nenek. "Maaf zahir dan batin, Nenek."',
          _S(_B.home, [_A(_R.nenek, 0.36, 0.58, 0.42), _A(_R.girl, 0.62, 0.62, 0.3, flip: true, tint: _purple)])),
      _P('Nenek hugged her. "We forgive each other and start fresh."',
          'Nenek memeluknya. "Kita saling memaafkan dan bermula semula."',
          _S(_B.home, [_A(_R.nenek, 0.42, 0.58, 0.42), _A(_R.girl, 0.58, 0.62, 0.3, flip: true, tint: _purple), _A(_R.heart, 0.5, 0.26, 0.1, motion: _M.float)])),
      _P('Neighbours came to visit. The table was full of rendang, ketupat and kuih!',
          'Jiran-jiran datang berkunjung. Meja penuh dengan rendang, ketupat dan kuih!',
          _S(_B.home, [_A(_R.ketupat, 0.3, 0.58, 0.12, motion: _M.bob), _A(_R.kuih, 0.5, 0.6, 0.12, motion: _M.bob), _A(_R.ketupat, 0.7, 0.58, 0.12, motion: _M.bob), _A(_R.atuk, 0.14, 0.56, 0.4), _A(_R.woman, 0.88, 0.56, 0.4, flip: true)])),
      _P('Sara\'s friend Mei Ling and her family came too. Everyone is welcome at an open house!',
          'Kawan Sara, Mei Ling dan keluarganya pun datang. Semua orang dialu-alukan di rumah terbuka!',
          _S(_B.kampung, [_A(_R.girl, 0.36, 0.62, 0.32, tint: _purple), _A(_R.girlPigtails, 0.62, 0.62, 0.32, flip: true, tint: _red), _A(_R.heart, 0.5, 0.3, 0.08, motion: _M.float)])),
      _P('At night, fireworks sparkled in the sky. Raya is about love and togetherness.',
          'Pada waktu malam, bunga api berkerlipan di langit. Raya ialah tentang kasih sayang dan kebersamaan.',
          _S(_B.kampung, night: true, [_A(_R.fireworks, 0.3, 0.2, 0.26, motion: _M.still), _A(_R.fireworks, 0.72, 0.16, 0.2, motion: _M.still, tint: 0xFF7CE0FF), _A(_R.girl, 0.4, 0.62, 0.3, tint: _purple), _A(_R.girlPigtails, 0.6, 0.62, 0.3, flip: true, tint: _red)])),
    ],
  ),
  StorySeed(
    key: 'pasar_malam',
    title: 'Counting at the Pasar Malam',
    titleMs: 'Mengira di Pasar Malam',
    description: 'Danial spends five ringgit wisely and counts every coin.',
    coverEmoji: '🪙',
    category: 'Math',
    ageGroup: 'primary',
    pages: [
      _P('Every Wednesday, there is a pasar malam near Danial\'s house.',
          'Setiap hari Rabu, ada pasar malam berhampiran rumah Danial.',
          _S(_B.market, night: true, [_A(_R.boy, 0.5, 0.62, 0.32, tint: 0xFFFF8A3D, motion: _M.hop)])),
      _P('Ibu gave Danial five ringgit. "You can buy food for our family."',
          'Ibu memberi Danial lima ringgit. "Kamu boleh beli makanan untuk keluarga kita."',
          _S(_B.home, night: true, [_A(_R.woman, 0.32, 0.56, 0.42), _A(_R.coins, 0.5, 0.46, 0.1, motion: _M.float), _A(_R.boy, 0.68, 0.62, 0.3, flip: true, tint: 0xFFFF8A3D)])),
      _P('The first stall sold apam balik for two ringgit.',
          'Gerai pertama menjual apam balik dengan harga dua ringgit.',
          _S(_B.market, night: true, [_A(_R.snackBag, 0.64, 0.5, 0.16, motion: _M.bob), _A(_R.boy, 0.34, 0.62, 0.32, tint: 0xFFFF8A3D, feel: _F.surprised)])),
      _P('Danial bought one. "Five take away two... I have three ringgit left!"',
          'Danial membeli satu. "Lima tolak dua... tinggal tiga ringgit!"',
          _S(_B.market, night: true, [_A(_R.boy, 0.36, 0.62, 0.32, tint: 0xFFFF8A3D), _A(_R.snackBag, 0.54, 0.6, 0.1, motion: _M.still), _A(_R.coins, 0.72, 0.46, 0.1, motion: _M.float)])),
      _P('Next was the air tebu stall. One cup of sugarcane juice cost one ringgit.',
          'Seterusnya gerai air tebu. Secawan air tebu berharga satu ringgit.',
          _S(_B.market, night: true, [_A(_R.cup, 0.64, 0.5, 0.16, motion: _M.bob), _A(_R.boy, 0.34, 0.62, 0.32, tint: 0xFFFF8A3D)])),
      _P('"Three take away one is two. I still have two ringgit," said Danial.',
          '"Tiga tolak satu jadi dua. Saya masih ada dua ringgit," kata Danial.',
          _S(_B.market, night: true, [_A(_R.boy, 0.36, 0.62, 0.32, tint: 0xFFFF8A3D), _A(_R.cup, 0.54, 0.6, 0.1, motion: _M.still), _A(_R.coins, 0.72, 0.46, 0.09, motion: _M.float)])),
      _P('Then he saw a toy car for five ringgit. Danial wanted it so much!',
          'Kemudian dia ternampak kereta mainan berharga lima ringgit. Danial sangat mahukannya!',
          _S(_B.market, night: true, [_A(_R.toyCar, 0.66, 0.52, 0.14, motion: _M.bob), _A(_R.boy, 0.34, 0.62, 0.32, tint: 0xFFFF8A3D, feel: _F.surprised)])),
      _P('"Two ringgit is not enough. And this money is for the family," he thought.',
          '"Dua ringgit tidak cukup. Lagipun wang ini untuk keluarga," fikirnya.',
          _S(_B.market, night: true, [_A(_R.boy, 0.5, 0.62, 0.32, tint: 0xFFFF8A3D, motion: _M.sway), _A(_R.heart, 0.5, 0.3, 0.08, motion: _M.float)])),
      _P('Danial bought two pisang goreng for one ringgit each. Now he had none left!',
          'Danial membeli dua pisang goreng, satu ringgit setiap satu. Kini wangnya sudah habis!',
          _S(_B.market, night: true, [_A(_R.boy, 0.34, 0.62, 0.32, tint: 0xFFFF8A3D, motion: _M.hop), _A(_R.snackBag, 0.58, 0.54, 0.12, motion: _M.bob), _A(_R.snackBag, 0.72, 0.54, 0.12, motion: _M.bob)])),
      _P('The family ate together. "You counted very well, Danial!" said Ibu.',
          'Keluarga makan bersama-sama. "Pandai Danial mengira!" kata Ibu.',
          _S(_B.home, night: true, [_A(_R.woman, 0.2, 0.56, 0.4), _A(_R.snackBag, 0.4, 0.58, 0.1, motion: _M.still), _A(_R.cup, 0.52, 0.58, 0.09, motion: _M.still), _A(_R.snackBag, 0.64, 0.58, 0.1, motion: _M.still), _A(_R.boy, 0.82, 0.62, 0.3, flip: true, tint: 0xFFFF8A3D)])),
    ],
  ),

  // ── Science & nature ─────────────────────────────────────────────────────
  StorySeed(
    key: 'water_drop',
    title: 'Titi the Water Drop',
    titleMs: 'Titi si Titis Air',
    description: 'Follow a little water drop around the water cycle.',
    coverEmoji: '💧',
    category: 'Science',
    ageGroup: 'all',
    pages: [
      _P('Titi was a tiny water drop living in the big blue sea.',
          'Titi ialah setitis air kecil yang tinggal di laut biru yang luas.',
          _S(_B.sea, [_A(_R.sun, 0.8, 0.16, 0.18, motion: _M.sway), _A(_R.raindrop, 0.46, 0.6, 0.16)])),
      _P('The sun shone warmly. Titi felt lighter and lighter...',
          'Matahari bersinar dengan panas. Titi berasa semakin ringan...',
          _S(_B.sea, [_A(_R.sun, 0.7, 0.18, 0.24, motion: _M.sway), _A(_R.raindrop, 0.4, 0.58, 0.15, feel: _F.surprised, motion: _M.float)])),
      _P('Whoosh! Titi turned into water vapour and floated up. This is evaporation!',
          'Wuss! Titi berubah menjadi wap air dan terapung ke atas. Ini dipanggil penyejatan!',
          _S(_B.sky, [_A(_R.raindrop, 0.5, 0.5, 0.16, motion: _M.float), _A(_R.raindrop, 0.3, 0.68, 0.08, motion: _M.float), _A(_R.raindrop, 0.7, 0.72, 0.08, motion: _M.float)])),
      _P('High up it was cold. Titi joined other drops to make a cloud. This is condensation!',
          'Di atas, udaranya sejuk. Titi berkumpul dengan titisan lain membentuk awan. Ini dipanggil kondensasi!',
          _S(_B.sky, [_A(_R.cloud, 0.5, 0.4, 0.3, motion: _M.float), _A(_R.raindrop, 0.26, 0.62, 0.08, motion: _M.float), _A(_R.raindrop, 0.74, 0.62, 0.08, motion: _M.float)])),
      _P('The cloud grew bigger and heavier, and turned grey.',
          'Awan itu menjadi semakin besar dan berat, lalu bertukar kelabu.',
          _S(_B.sky, [_A(_R.cloud, 0.5, 0.42, 0.4, tint: _grey, feel: _F.surprised, motion: _M.float)])),
      _P('Pitter-patter! Titi fell as rain on a green forest. This is precipitation!',
          'Tik-tik-tik! Titi jatuh sebagai hujan ke atas hutan hijau. Ini dipanggil kerpasan!',
          _S(_B.rainforest, rain: true, [_A(_R.cloud, 0.5, 0.14, 0.2, tint: _grey, motion: _M.fly), _A(_R.raindrop, 0.5, 0.46, 0.14, motion: _M.hop)])),
      _P('Titi gave a drink to a thirsty little plant.',
          'Titi memberi minuman kepada anak pokok yang dahaga.',
          _S(_B.garden, [_A(_R.sprout, 0.56, 0.62, 0.22, motion: _M.sway), _A(_R.raindrop, 0.36, 0.44, 0.12, motion: _M.float)])),
      _P('Then Titi flowed into a river, travelling past fish and rocks.',
          'Kemudian Titi mengalir ke dalam sungai, melepasi ikan dan batu.',
          _S(_B.river, [_A(_R.raindrop, 0.36, 0.52, 0.12, motion: _M.fly), _A(_R.fish, 0.68, 0.56, 0.08, motion: _M.fly, flip: true, tint: 0xFFFF9F43)])),
      _P('At last, the river carried Titi back home to the sea.',
          'Akhirnya, sungai membawa Titi pulang ke laut.',
          _S(_B.sea, [_A(_R.raindrop, 0.5, 0.58, 0.16, motion: _M.hop), _A(_R.fish, 0.24, 0.68, 0.08, motion: _M.fly)])),
      _P('"I will go round and round again!" said Titi. This journey is the water cycle.',
          '"Saya akan berkitar lagi dan lagi!" kata Titi. Perjalanan ini dipanggil kitaran air.',
          _S(_B.sea, [_A(_R.sun, 0.18, 0.16, 0.16, motion: _M.sway), _A(_R.cloud, 0.78, 0.18, 0.18, motion: _M.fly), _A(_R.raindrop, 0.5, 0.6, 0.16, motion: _M.hop), _A(_R.rainbow, 0.5, 0.36, 0.3, motion: _M.still)])),
    ],
  ),
  StorySeed(
    key: 'butterfly',
    title: 'Ulu\'s Big Change',
    titleMs: 'Ulu Menjadi Rama-rama',
    description: 'A hungry caterpillar grows into a butterfly.',
    coverEmoji: '🦋',
    category: 'Science',
    ageGroup: 'preschool',
    pages: [
      _P('On a green leaf, there was a tiny egg.',
          'Di atas sehelai daun hijau, ada sebiji telur kecil.',
          _S(_B.garden, [_A(_R.egg, 0.5, 0.54, 0.22, motion: _M.sway)])),
      _P('Pop! Out came a hungry little caterpillar named Ulu.',
          'Pop! Keluarlah seekor beluncas kecil yang lapar bernama Ulu.',
          _S(_B.garden, [_A(_R.caterpillar, 0.5, 0.6, 0.16, feel: _F.surprised)])),
      _P('Ulu ate leaves on Monday, Tuesday and Wednesday. Munch, munch!',
          'Ulu makan daun pada hari Isnin, Selasa dan Rabu. Ngap, ngap!',
          _S(_B.garden, [_A(_R.caterpillar, 0.44, 0.62, 0.16, motion: _M.sway), _A(_R.sprout, 0.72, 0.62, 0.18, motion: _M.still)])),
      _P('Ulu ate and ate until he grew big and round.',
          'Ulu makan dan terus makan sehingga dia menjadi besar dan gemuk.',
          _S(_B.garden, [_A(_R.caterpillar, 0.5, 0.6, 0.26, motion: _M.bob)])),
      _P('Ulu felt sleepy. He hung upside down from a twig.',
          'Ulu berasa mengantuk. Dia bergantung terbalik pada sebatang ranting.',
          _S(_B.garden, [_A(_R.caterpillar, 0.5, 0.56, 0.18, feel: _F.sleepy, motion: _M.sway)])),
      _P('Ulu wrapped himself up and became a pupa. He rested for many days.',
          'Ulu membalut dirinya lalu menjadi pupa di dalam kepompong. Dia berehat selama beberapa hari.',
          _S(_B.garden, [_A(_R.cocoon, 0.5, 0.42, 0.34, motion: _M.sway)])),
      _P('Inside, something amazing was happening. Ulu was changing!',
          'Di dalamnya, sesuatu yang menakjubkan sedang berlaku. Ulu sedang berubah!',
          _S(_B.garden, night: true, [_A(_R.cocoon, 0.5, 0.42, 0.34, motion: _M.sway), _A(_R.star, 0.3, 0.3, 0.08, motion: _M.float), _A(_R.star, 0.7, 0.36, 0.06, motion: _M.float)])),
      _P('One morning, the pupa cracked open. Out came... wings!',
          'Pada suatu pagi, kepompong itu merekah. Keluarlah... sayap!',
          _S(_B.garden, [_A(_R.cocoon, 0.36, 0.38, 0.28, motion: _M.still), _A(_R.butterfly, 0.62, 0.5, 0.2, motion: _M.float)])),
      _P('Ulu was now a beautiful butterfly! He flew from flower to flower.',
          'Ulu kini seekor rama-rama yang cantik! Dia terbang dari bunga ke bunga.',
          _S(_B.garden, [_A(_R.butterfly, 0.4, 0.4, 0.24, motion: _M.fly), _A(_R.butterfly, 0.76, 0.26, 0.12, motion: _M.fly, tint: 0xFF5AC8FA), _A(_R.sun, 0.14, 0.14, 0.14, motion: _M.sway)])),
      _P('Egg, caterpillar, pupa, butterfly. That is the life cycle of a butterfly!',
          'Telur, beluncas, pupa, rama-rama. Itulah kitaran hidup rama-rama!',
          _S(_B.garden, [_A(_R.egg, 0.14, 0.58, 0.14, motion: _M.still), _A(_R.caterpillar, 0.38, 0.62, 0.1, motion: _M.still), _A(_R.cocoon, 0.62, 0.52, 0.2, motion: _M.still), _A(_R.butterfly, 0.86, 0.54, 0.14, motion: _M.float)])),
    ],
  ),
  StorySeed(
    key: 'space_trip',
    title: 'Nadia Visits the Planets',
    titleMs: 'Nadia Melawat Planet',
    description: 'A dream trip past every planet in our solar system.',
    coverEmoji: '🚀',
    category: 'Science',
    ageGroup: 'primary',
    pages: [
      _P('Nadia loved looking at the night sky. "I want to visit the planets!"',
          'Nadia suka melihat langit malam. "Saya mahu melawat planet-planet!"',
          _S(_B.kampung, night: true, [_A(_R.girlPigtails, 0.5, 0.62, 0.32, tint: 0xFF5B6EF5), _A(_R.star, 0.3, 0.2, 0.08, motion: _M.float)])),
      _P('In her dream, Nadia flew in a shiny rocket. Three, two, one, blast off!',
          'Dalam mimpinya, Nadia terbang dengan roket yang berkilat. Tiga, dua, satu, lepas landas!',
          _S(_B.space, [_A(_R.rocket, 0.5, 0.46, 0.44, motion: _M.float), _A(_R.earth, 0.18, 0.72, 0.3, motion: _M.still)])),
      _P('First stop: Mercury, the planet closest to the Sun. It is very hot!',
          'Hentian pertama: Utarid, planet yang paling hampir dengan Matahari. Ia sangat panas!',
          _S(_B.space, [_A(_R.sun, 0.12, 0.3, 0.5, motion: _M.sway), _A(_R.planet, 0.58, 0.44, 0.14, tint: 0xFFA8A29E, motion: _M.float), _A(_R.rocket, 0.82, 0.62, 0.2, motion: _M.fly)])),
      _P('Next was Venus, the brightest planet in our night sky.',
          'Seterusnya Zuhrah, planet yang paling terang di langit malam kita.',
          _S(_B.space, [_A(_R.planet, 0.46, 0.4, 0.24, tint: 0xFFF2C46D, motion: _M.float), _A(_R.rocket, 0.8, 0.7, 0.2, motion: _M.fly)])),
      _P('Then Nadia waved at Earth, our blue and green home.',
          'Kemudian Nadia melambai ke arah Bumi, rumah kita yang biru dan hijau.',
          _S(_B.space, [_A(_R.earth, 0.44, 0.42, 0.3, motion: _M.float), _A(_R.moon, 0.72, 0.22, 0.1, motion: _M.float), _A(_R.rocket, 0.8, 0.7, 0.2, motion: _M.fly)])),
      _P('Mars was red and dusty. It is called the Red Planet!',
          'Marikh berwarna merah dan berdebu. Ia digelar Planet Merah!',
          _S(_B.space, [_A(_R.planet, 0.46, 0.42, 0.22, tint: 0xFFD9573B, motion: _M.float), _A(_R.rocket, 0.8, 0.7, 0.2, motion: _M.fly)])),
      _P('Jupiter was the biggest planet of all, with a giant red spot.',
          'Musytari ialah planet yang paling besar, dengan tompok merah yang gergasi.',
          _S(_B.space, [_A(_R.planet, 0.44, 0.42, 0.46, tint: 0xFFD9A066, motion: _M.float), _A(_R.rocket, 0.84, 0.62, 0.16, motion: _M.fly)])),
      _P('Saturn had beautiful rings made of ice and rock.',
          'Zuhal mempunyai gelang yang cantik diperbuat daripada ais dan batu.',
          _S(_B.space, [_A(_R.planetRinged, 0.46, 0.42, 0.3, tint: 0xFFE8C77A, motion: _M.float), _A(_R.rocket, 0.84, 0.62, 0.16, motion: _M.fly)])),
      _P('Far, far away were Uranus and Neptune, cold and blue.',
          'Jauh di sana ada Uranus dan Neptun yang sejuk dan berwarna biru.',
          _S(_B.space, [_A(_R.planet, 0.32, 0.34, 0.2, tint: 0xFF8EE3E8, motion: _M.float), _A(_R.planet, 0.66, 0.5, 0.2, tint: 0xFF3E6FE0, motion: _M.float), _A(_R.rocket, 0.84, 0.62, 0.14, motion: _M.fly)])),
      _P('Nadia woke up and smiled. "When I grow up, I will be an astronaut!"',
          'Nadia terjaga dan tersenyum. "Bila besar nanti, saya mahu jadi angkasawan!"',
          _S(_B.home, night: true, [_A(_R.girlPigtails, 0.46, 0.62, 0.32, tint: 0xFF5B6EF5, motion: _M.hop), _A(_R.rocket, 0.72, 0.42, 0.16, motion: _M.float)])),
    ],
  ),
  StorySeed(
    key: 'baby_turtle',
    title: 'Pina the Baby Turtle',
    titleMs: 'Pina si Anak Penyu',
    description: 'A baby sea turtle makes her way from the beach to the ocean.',
    coverEmoji: '🌊',
    category: 'Science',
    ageGroup: 'all',
    pages: [
      _P('On a beach in Terengganu, a mother turtle dug a hole in the sand.',
          'Di sebuah pantai di Terengganu, seekor ibu penyu menggali lubang di dalam pasir.',
          _S(_B.beach, night: true, [_A(_R.turtle, 0.5, 0.64, 0.22, motion: _M.sway)])),
      _P('She laid many round eggs, covered them, and went back to the sea.',
          'Dia bertelur banyak telur yang bulat, menimbusnya, lalu kembali ke laut.',
          _S(_B.beach, night: true, [_A(_R.egg, 0.4, 0.68, 0.11, motion: _M.still, tint: 0xFFF7F1E3), _A(_R.egg, 0.5, 0.7, 0.11, motion: _M.still, tint: 0xFFF7F1E3), _A(_R.egg, 0.6, 0.68, 0.11, motion: _M.still, tint: 0xFFF7F1E3), _A(_R.turtle, 0.66, 0.5, 0.18, flip: true)])),
      _P('For about fifty days, the warm sand kept the eggs safe.',
          'Selama kira-kira lima puluh hari, pasir yang hangat menjaga telur-telur itu.',
          _S(_B.beach, [_A(_R.sun, 0.8, 0.16, 0.18, motion: _M.sway), _A(_R.egg, 0.44, 0.7, 0.11, motion: _M.still, tint: 0xFFF7F1E3), _A(_R.egg, 0.56, 0.7, 0.11, motion: _M.still, tint: 0xFFF7F1E3)])),
      _P('Crack! A tiny turtle named Pina popped out of the sand.',
          'Krek! Seekor anak penyu kecil bernama Pina keluar dari pasir.',
          _S(_B.beach, night: true, [_A(_R.turtle, 0.5, 0.66, 0.12, feel: _F.surprised, motion: _M.hop)])),
      _P('Pina saw the moonlight shining on the water. "The sea is that way!"',
          'Pina nampak cahaya bulan bersinar di atas air. "Laut di sebelah sana!"',
          _S(_B.beach, night: true, [_A(_R.turtle, 0.46, 0.66, 0.12), _A(_R.moon, 0.74, 0.16, 0.14, motion: _M.float)])),
      _P('Pina crawled and crawled. Crabs and birds were watching!',
          'Pina merangkak dan terus merangkak. Ketam dan burung sedang memerhati!',
          _S(_B.beach, [_A(_R.turtle, 0.5, 0.66, 0.12), _A(_R.crab, 0.2, 0.66, 0.1, motion: _M.sway), _A(_R.bird, 0.74, 0.26, 0.1, motion: _M.fly, flip: true)])),
      _P('Kind volunteers kept the path safe. "Go, little turtle!"',
          'Sukarelawan yang baik hati menjaga laluan itu. "Teruskan, anak penyu!"',
          _S(_B.beach, [_A(_R.girl, 0.18, 0.58, 0.3, tint: 0xFF2BB5A0), _A(_R.turtle, 0.5, 0.68, 0.1), _A(_R.boy, 0.82, 0.58, 0.3, flip: true, tint: 0xFF2BB5A0)])),
      _P('Splash! Pina swam into the waves for the very first time.',
          'Plup! Pina berenang ke dalam ombak buat kali pertama.',
          _S(_B.underwater, [_A(_R.turtle, 0.5, 0.36, 0.18, motion: _M.fly)])),
      _P('The ocean was full of fish, coral and seaweed. Pina\'s new home!',
          'Lautan penuh dengan ikan, batu karang dan rumpai laut. Rumah baharu Pina!',
          _S(_B.underwater, [_A(_R.turtle, 0.46, 0.38, 0.18, motion: _M.fly), _A(_R.fish, 0.2, 0.22, 0.08, motion: _M.fly, tint: 0xFFFF9F43), _A(_R.fish, 0.8, 0.5, 0.08, motion: _M.fly, flip: true, tint: 0xFFFFD24A)])),
      _P('One day, Pina will return to the same beach. Let\'s keep beaches clean for turtles!',
          'Suatu hari nanti, Pina akan kembali ke pantai yang sama. Mari jaga kebersihan pantai untuk penyu!',
          _S(_B.beach, [_A(_R.girl, 0.3, 0.58, 0.3, tint: 0xFF2BB5A0), _A(_R.heart, 0.5, 0.36, 0.08, motion: _M.float), _A(_R.turtle, 0.68, 0.66, 0.12, flip: true)])),
    ],
  ),
];
