import 'story_library.dart';

/// Which synthesised sound each story actor makes when tapped, and which
/// ambient loop plays behind each shot.
///
/// The audio files are generated by `tool/synth_story_sounds.py`:
/// `assets/audio/story_<sfx>.m4a` and `assets/audio/amb_<loop>.m4a`.

String storyActorSfx(StoryActor actor) => switch (actor) {
      StoryActor.boy ||
      StoryActor.girl ||
      StoryActor.girlPigtails ||
      StoryActor.woman ||
      StoryActor.atuk ||
      StoryActor.nenek =>
        'pop',
      StoryActor.ant => 'patter',
      StoryActor.grasshopper => 'chirp',
      StoryActor.tortoise => 'bonk',
      StoryActor.hare => 'boing',
      StoryActor.kancil => 'hop',
      StoryActor.crocodile => 'chomp',
      StoryActor.turtle || StoryActor.fish => 'bubble',
      StoryActor.crab => 'clack',
      StoryActor.bird => 'tweet',
      StoryActor.butterfly || StoryActor.flag => 'flutter',
      StoryActor.caterpillar => 'munch',
      StoryActor.egg || StoryActor.cocoon => 'crack',
      StoryActor.sun || StoryActor.star || StoryActor.heart => 'twinkle',
      StoryActor.coins => 'coin',
      StoryActor.cloud || StoryActor.rocket || StoryActor.kite || StoryActor.umbrella => 'whoosh',
      StoryActor.raindrop => 'drip',
      StoryActor.moon || StoryActor.ketupat || StoryActor.pelita => 'chime',
      StoryActor.planet || StoryActor.planetRinged || StoryActor.earth => 'space',
      StoryActor.rainbow => 'gliss',
      StoryActor.fireworks => 'firework',
      StoryActor.toyCar => 'beep',
      StoryActor.sprout ||
      StoryActor.rambutan ||
      StoryActor.wallet ||
      StoryActor.basket ||
      StoryActor.grain ||
      StoryActor.kuih ||
      StoryActor.cup ||
      StoryActor.snackBag =>
        'pop',
    };

/// The ambient loop behind a shot. Rain is layered on separately.
String storyAmbientFor(StoryShot shot) {
  switch (shot.backdrop) {
    case StoryBackdrop.home:
      return 'home';
    case StoryBackdrop.market:
      return 'market';
    case StoryBackdrop.rainforest:
      return 'forest';
    case StoryBackdrop.river:
      return 'river';
    case StoryBackdrop.beach:
    case StoryBackdrop.sea:
      return 'waves';
    case StoryBackdrop.underwater:
      return 'underwater';
    case StoryBackdrop.space:
      return 'space';
    case StoryBackdrop.sky:
      return 'wind';
    case StoryBackdrop.kampung:
    case StoryBackdrop.school:
    case StoryBackdrop.garden:
    case StoryBackdrop.field:
      return shot.night ? 'night' : 'day';
  }
}

/// Every sound file the story library can ask for, for asset checks.
Set<String> get kStorySfxNames => {for (final a in StoryActor.values) storyActorSfx(a)};

const Set<String> kStoryAmbientNames = {
  'day', 'night', 'forest', 'river', 'waves', 'underwater', 'space', 'market', 'home', 'wind', 'rain',
};
